### PR TITLE
.NET Standard 2.0 support added

### PR DESCRIPTION
**Pull request by faryu**
Updated the project configuration to the new csproj format and added .NET Standard 2.0 as an additional target framework.
(Needs Visual Studio 2017)

### CODE REVIEW

**Comment by rix0rrr** [comment]
I'm all for the .NET standard support, but not too keen on the neverending march of Visual Studio project file deprecation :(

Is this really how it is in Visual Studio land?

**Comment by JohnLouderback** [comment]
@rix0rrr Can this get merged? I need this support for a project. It doesn't appear to work for Xamarin Forms.

**Comment by JohnLouderback** [comment]
@rix0rrr Thanks for merging this in. Would you be able to update the Nuget package as well?

**Comment by rix0rrr** [comment]
Ah yes. Will do that later tonight.

**Comment by rix0rrr** [comment]
I regret merging this, since my Visual Studio doesn't open the csproj anymore :(

**Comment by JohnLouderback** [comment]
@rix0rrr  Yeah, from what I've always seen, trying to support a library and the latest .NET features and not always using the latest Visual Studio version can be a bit of an uphill battle. If it were me, I'd download the latest Visual Studio 2017. It takes forever to install, but it's free, fortunately. I'd say it's worth it though, since .NET Core/.NET Standard are becoming ubiquitous whereas the other frameworks seem to be becoming more legacy than anything.

**Comment by rix0rrr** [comment]
Okay after spending half an hour uninstall and installing 2017, the reference to .NETStandard 2.0 doesn't resolve? What else do I need to install?

Man, not enjoying stepping back into the Microsoft ecosystem

**Comment by rix0rrr** [comment]
Woohoo I think I did it!

**Pull request merged**
